#!/bin/bash

set -ex

DEST=${PWD}/assets/bin
GOPATH=${PWD}/deps
mkdir -p $GOPATH

export GOPATH
go get github.com/geofffranks/spruce
cd ${GOPATH}/src/github.com/geofffranks/spruce
gox -osarch linux/amd64
cp spruce_linux_amd64 ${DEST}/spruce

for flavor in v0.12.0
do
	git checkout ${flavor}
	gox -osarch linux/amd64
	cp spruce_linux_amd64 ${DEST}/spruce-${flavor}
done
cd -

rm -rf ${PWD}/deps
ls -lh ${DEST}
