groups:
- jobs:
  - deploy
  name: deploy
- jobs:
  - docker
  name: image
jobs:
- name: docker
  plan:
  - get: recipe
    resource: docker-recipe
    trigger: true
  - get: cf-cli
    trigger: true
  - config:
      image: docker:///busybox
      inputs:
      - name: recipe
        path: .
      - name: cf-cli
        path: recipe/ci/image/cf-cli
      platform: linux
      run:
        path: echo
    task: combine
  - params:
      build: combine/recipe/ci/image
    put: docker-image
  public: true
  serial: true
- name: deploy
  plan:
  - do:
    - aggregate:
      - get: play.spruce.cf
        resource: play.spruce.cf.git
        trigger: true
      - get: spruce
        resource: spruce.git
        trigger: true
    - config:
        image: docker:///clutteredraisins/play.spruce.cf-pipeline
        inputs:
        - name: play.spruce.cf
          path: play.spruce.cf/
        - name: spruce
          path: spruce/
        platform: linux
        run:
          args:
          - v0.12.0
          path: ./play.spruce.cf/ci/redeploy
      task: deploy
  public: true
  serial: true
resources:
- name: docker-recipe
  source:
    branch: pipeline
    paths:
    - ci/image/*
    uri: https://github.com/filefrog/play.spruce.cf.git
  type: git
- name: cf-cli
  source:
    bucket: go-cli
    regexp: releases/v(.*)/cf-linux-amd64.tgz
  type: s3
- name: docker-image
  source:
    email: {{docker-hub-email}}
    password: {{docker-hub-password}}
    repository: clutteredraisins/play.spruce.cf-pipeline
    username: {{docker-hub-username}}
  type: docker-image
- name: play.spruce.cf.git
  source:
    branch: pipeline
    uri: https://github.com/filefrog/play.spruce.cf.git
  type: git
- name: spruce.git
  source:
    branch: master
    uri: https://github.com/geofffranks/spruce.git
  type: git

